### ISSUE TITLE
There is unexpected error with com.epam.reportportal.cucumber.StepReporter - It does not implement cucumber.api.Plugin

### ISSUE THREAD

**Issue by Hunterok1** [reportportal/agent-java-cucumber#10]
Reproduces with agent-java-cucumber v.3.0.1
Gherkin version - 2.12.2

During cucumber run the error occurs:
cucumber.runtime.CucumberException: Couldn't load plugin class: com.epam.reportportal.cucumber.StepReporter. It does not implement cucumber.api.Plugin

**Comment by avarabyeu** [comment]
@Hunterok1 which version of cucumberJVM do you use?

**Comment by Hunterok1** [comment]
Cucumber version 2.3.1

**Comment by avarabyeu** [comment]
@Hunterok1 unfortunately, we do not support latest versions of cucumber. Our agent should be updated (or even re-implemented) for 2x cucumber generation

**Comment by Rome3333** [comment]
Hi @avarabyeu, @DzmitryHumianiuk,

Any approximate estimates around cucumber 2x support? Is it already planned somehow? Cucumber 2 has been released half a year ago with some really major changes which we are really need to have on our project and would be really nice to have support in report portal.

Thank you!

**Comment by ruzeynalov** [comment]
Guys, we need support for Cucumber version 2.x. I would really appreciate input from original developers of report portal agent. Thank you )

**Comment by DzmitryHumianiuk** [comment]
@ruzeynalov team focused on features development of core product.

We have no tangible plans for cucumber agent updates.
But we gladly will help with review of PRs

**Comment by rakeshmishra36** [comment]
I am also getting the same issue with the latest version.

Gherkin version - 2.12.2

<groupId>io.cucumber</groupId>
<artifactId>cucumber-core</artifactId>
<version>2.4.0</version>

**Comment by nstbushneva** [comment]
We were considering using this tool in our project but unfortunately found this issue as a huge blocker. So +1 vote for this one.

**Comment by DzmitryHumianiuk** [comment]
@nstbushneva @Hunterok1 @rakeshmishra36 @ruzeynalov @Rome3333 
https://github.com/reportportal/agent-java-cucumber2
https://github.com/reportportal/agent-java-cucumber3

**Comment by DzmitryHumianiuk** [comment]
@indrabt somebody from contributors, proposed to send PR.
we created the repo, but didn't receive it.

as i remember, there is no much of difference in cucumber3 and 4.
and cucumber 3, is just few updates in version 2.

**Comment by indrabt** [comment]
@DzmitryHumianiuk  Thanks for your response . Some of the features like data table in cucumber 3 was being used by our team here. unfortunately we can't downgrade to cucumber 2 because we will have to refactor all our code and at the same time we want to utilise report portal here .

**Comment by DzmitryHumianiuk** [comment]
@indrabt we opened position for SDET (Software Developer Engineer in Test).
i assume he will be responsible for this staff to be up-to-date.

**Comment by MithunDavid** [comment]
I am still facing this issue while using scenario/step reports. We are using cucumber-java and cucumber-testng in our framework. I even tried with latest agent-java-cucumber-5.0.0-BETA-0. Can you please update the compatibility matrix for the latest versions.

**Comment by DzmitryHumianiuk** [comment]
@MithunDavid v5.x.x agent will work with ReportPortal v5 only.

for ReportPortal v4 use latest v4.x.x agent.

and could you give more details on issue?

**Comment by evgenytkachenko** [comment]
I have the same issue with RP v5 and agent v5. I tried different versions of cucumber/gherkin from the table "Compatibility matrix for cucumber agents" - does not work.

It works only with the ancient version of  cucumber/gherkin - 1.2.5/2.12.2

Please, help

**Comment by DzmitryHumianiuk** [comment]
@HardNorth will take a look shortly.
we do stabilization all java related agents and examples.

try examples from here: https://github.com/reportportal/examples-java

**Comment by evgenytkachenko** [comment]
@DzmitryHumianiuk  it helped
I had to use
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber**4**</artifactId>
            <version>5.0.0-BETA-1</version>
        </dependency>

I used
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber</artifactId>
            <version>5.0.0-BETA-1</version>
        </dependency>

**Comment by vinitmalhotra** [comment]
Hi All, I am trying to run Report Portal with Cucumber 6 but getting below error. Can anyone please guide how to use it with Cucumber 6.

[ERROR] setUpClass(testRunner.RunCucumberTest)  Time elapsed: 1.711 s  <<< FAILURE!
io.cucumber.core.exception.CucumberException: Couldn't load plugin class: com.epam.reportportal.cucumber.ScenarioReporter
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.cucumber.ScenarioReporter

My POM.xml contains following

<dependency>
      <groupId>com.epam.reportportal</groupId>
      <artifactId>client-java</artifactId>
      <version>5.1.0-RC-6</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.epam.reportportal</groupId>
      <artifactId>commons-model</artifactId>
      <version>5.0.0</version>
      <scope>compile</scope>
    </dependency>
 <groupId>io.cucumber</groupId>
      <artifactId>cucumber-java</artifactId>
      <version>6.0.0</version>
      <scope>compile</scope>

**Comment by HardNorth** [comment]
@vinitmalhotra you need to use **agent-java-cucumber6**

**Comment by Mahesh81** [comment]
@HardNorth 
We are setting up serenity framework with following pom.xml dependency 
        <dependency>
            <groupId>com.github.invictum</groupId>
            <artifactId>serenity-reportportal-integration</artifactId>
            <version>1.5.8</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber</artifactId>
            <version>5.1.0-RC-2</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.0.3</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber5</artifactId>
            <version>2.2.5</version>
        </dependency>

Used the stepreporter plugin 
		plugin = {
				"com.epam.reportportal.cucumber.StepReporter"
		}

we get the following error 
**io.cucumber.core.exception.CucumberException: Couldn't load plugin class: com.epam.reportportal.cucumber.StepReporter. It does not implement io.cucumber.plugin.Plugin**

Can you please help us if there is any version mismatch

**Comment by HardNorth** [comment]
@Mahesh81 You need to use `agent-java-cucumber5` version `5.1.0-RC-2`

**Comment by dragos-panzaru-md** [comment]
With the following pom.xml
[      <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>7.2.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>3.2.5</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber</artifactId>
            <version>5.1.3</version>
        </dependency>](url)
I encounter the same issue:
[java.lang.IllegalArgumentException: The plugin specification 'com.epam.reportportal.cucumber.StepReporter' has a problem:

Could not load plugin class 'com.epam.reportportal.cucumber.StepReporter'.](url)
when using the step reporter
[@CucumberOptions(
        plugin = {"com.epam.reportportal.cucumber.StepReporter"})](url)

**Comment by dragos-panzaru-md** [comment]
@HardNorth Yes you were correct. After making the necessary adjustment in pom.xml (changed agent-java-cucumber to agent-java-cucumber6) now I don't get any error anymore on test execution, but I don't see any report in report portal. 
I have the reportportal.properties in the root project folder, with the following content copied from the user profile section in report portal:
```
rp.endpoint = <report.portal.address>
rp.uuid = <access.token>
rp.launch = <launch.name>
rp.project = <project.name>
```
and for test execution I run the 
```
mvn clean install
``` 
command.
As a side note, the test is executed properly and the serenity report is also generated correctly

**Comment by dragos-panzaru-md** [comment]
@HardNorth Thank you for the quick response. If I use serenity with junit5 and cucumber do I need to integrate also junit with report portal using agent-java-junit5, or is enough to integrate cucumber with report portal using agent-java-cucumber6?
The reason for asking this is that, when I execute the following command:
```
mvn clean install
```
I don't see in the logs any reference to report portal.

**Comment by HardNorth** [comment]
@dragos-panzaru-md just `agent-java-cucumber6` should be enough. But I can't see your system and configurations to say what's exactly wrong, you should investigate that yourself.
