### ISSUE TITLE
Disabled To Invistigate feature

### ISSUE THREAD

**Issue by vladyslav-zahorodnii** [reportportal/agent-java-cucumber#13]
Can't investigate type of defect.

**Comment by vladyslav-zahorodnii** [comment]
![bug3](https://user-images.githubusercontent.com/34536592/38094607-ec6e47f6-3376-11e8-8776-bb405482fc73.PNG)
![bug4](https://user-images.githubusercontent.com/34536592/38094608-ec8dc1d0-3376-11e8-856e-f497dfb1ed9d.PNG)
![bug5](https://user-images.githubusercontent.com/34536592/38094609-ecac78be-3376-11e8-807d-be3d732f1fcf.PNG)
![bug1](https://user-images.githubusercontent.com/34536592/38094611-eceb5110-3376-11e8-8d18-b9b905d5f42d.PNG)
![bug2](https://user-images.githubusercontent.com/34536592/38094612-ed091e02-3376-11e8-8414-7627bade1b71.PNG)

**Comment by avarabyeu** [comment]
@vladyslav-zahorodnii It seems you have incorrect statistics calculation strategy. i've changed it to default one. Could you please try again and let me know if it helped

**Comment by vladyslav-zahorodnii** [comment]
@avarabyeu I did not change anything today, 04/04/18 I run tests, and the button 'To Investigate' appeared. Apparently you have something corrected.
