### ISSUE TITLE
java.lang.NoClassDefFoundError: gherkin/IGherkinDialectProvider

### ISSUE THREAD

**Issue by lgoldstein** [reportportal/agent-java-cucumber#25]
This is a reopen of [issue #32](https://github.com/reportportal/agent-java-cucumber/issues/23). Still occurs with _Cucumber_ 4.1.1 and _Gherkin_ 6.0.14 - despite having cleaned and _m2_ repository and re-fetching the relevant artifacts (as originally suggested in the issue)

**Comment by IlyasPatel** [comment]
When I downgrade the gherkin dependency to the following, then everything compiles:
`compile 'io.cucumber:gherkin:5.1.0'`

From version 6.0.0, then I get the error above.

**Comment by Srinija25** [comment]
I am facing the same problem. I downgraded to Gherkin 5.1.0 . It did not work for me.

My Cucumber java version is 4.2

**Comment by lgoldstein** [comment]
Still occurs even with version 4.2.2

**Comment by filland** [comment]
@lgoldstein @IlyasPatel  @Srinija25 

To avoid problems with versions mess there is a compatibility matrix - https://github.com/reportportal/agent-java-cucumber#compatibility-matrix-for-cucumber-agents

This table might help you to choose the right versions of all сucumber libs.

**Comment by Imspaliwal** [comment]
@filland I have used dependencies as per matrix you have provided but it is not working for me and I am getting same error. 

![image](https://user-images.githubusercontent.com/18319606/56467809-5f895b80-6441-11e9-86c9-983b85a71a95.png)

**Comment by filland** [comment]
@Imspaliwal what version of cucumber java do you want to use ?
