### ISSUE TITLE
Cucumber: Test never ends - Threads are in wait state

### ISSUE THREAD

**Issue by Vitovtx** [reportportal/agent-java-cucumber#7]
For running performance tests our team use Cucumber cli runner implementation cucumber.api.cli.Main. With Report Portal v.2 and related libs reportportal-client, reportportal-log4j-integration, reportportal-client-core v.2.1.6 this approach works without issues.
After migration to Report Portal v.3 we found that the same code work with issues with new RPv3 libs: 
```
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber</artifactId>
			<version>3.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>3.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>commons-model</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>client-java</artifactId>
			<version>3.0.10</version>
		</dependency>
```
Test run never ends, looks like because of threads UrlChecker, RxComputationThreadPool, RxSchedulerPurge waiting state. 
Test project is created to reproduce this issue on any env, last actual RP libs version are included.
https://github.com/Vitovtx/reproduceThreadsFailure/

**Comment by avarabyeu** [comment]
@Vitovtx thank you for the issue. Stale thread is owned by apache async http client thread pool. In the latest versions we fix that problem. Issue is supposed to be resolved in client v.4
