### ISSUE TITLE
How to gradle build the version 5.0.x ? Exception in "signing.gradle"

### ISSUE THREAD

**Issue by sisihi** [reportportal/agent-java-cucumber#70]
Hi, 

I am trying to build the commit e348b376a5a5fe54165f198842e8d40fc21c0019 locally. 

I used the "gradle build" in the project folder and encountered the following failure:

![image](https://user-images.githubusercontent.com/16377386/121501108-7fa97980-ca11-11eb-8c40-8c642e610699.png)

It looks like I need to prepare a credential as the parameters in build time to do the signing. 

How can I get such a credential to have the lib built successfully?

Thanks for the help.

**Comment by HardNorth** [comment]
@sisihi please use gradle wrapper for building: 
![Screen Shot 2021-06-10 at 2 02 19 PM](https://user-images.githubusercontent.com/4364466/121514272-81187900-c9f4-11eb-94dc-e81ab7cbae05.png)
`
