### ISSUE TITLE
Could not load plugin class 'com.epam.reportportal.cucumber.ScenarioReporter'.

### ISSUE THREAD

**Issue by Skannan612** [reportportal/agent-java-cucumber#94]
java.lang.IllegalArgumentException: The plugin specification 'com.epam.reportportal.cucumber.ScenarioReporter' has a problem:
Could not load plugin class 'com.epam.reportportal.cucumber.ScenarioReporter'.

Plugin specifications should have the format of PLUGIN[:[PATH|[URI [OPTIONS]]]

Valid values for PLUGIN are: html, json, junit, message, pretty, progress, rerun, summary, teamcity, testng, timeline, unused, usage

PLUGIN can also be a fully qualified class name, allowing registration of 3rd party plugins. The 3rd party plugin must implement io.cucumber.plugin.Plugin

I tried with different cucumber versions

**Comment by HardNorth** [comment]
The issue does not follow our mandatory template.
