### ISSUE TITLE
How to get single launch for single run

### ISSUE THREAD

**Issue by silwalrajan** [reportportal/agent-java-cucumber#95]
**Is your feature request related to a problem? Please describe.**
1. Migrated from Cucumber 4 to 6 and integrated report portal into the project
2. Contains 2 runner files
3. When running the project, Could see 2 launches are getting launched on report portal, one for each runner file which is not expected

**Describe the solution you'd like**
I require a single launch which shows result of both both launches(runner files)

Note: It is working fine in extent reports
![image](https://github.com/reportportal/agent-java-cucumber/assets/86878134/1079b26c-8359-40dc-b7a9-d0b865e123e9)

**Comment by silwalrajan** [comment]
I have used below configurations
<dependency>		
			<groupId>com.epam.reportportal</groupId>	
			<artifactId>agent-java-cucumber6</artifactId>	
			 <version>5.1.3</version>	
		</dependency> 	
		<dependency>	
		    <groupId>com.epam.reportportal</groupId>	
		    <artifactId>logger-java-log4j</artifactId>	
		    <version>5.1.4</version>	
		</dependency>	
<dependency>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-java</artifactId>
				<version>6.10.4</version>
			</dependency>
			<dependency>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-junit</artifactId>
				<version>6.10.4</version>
			</dependency>
			<dependency>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-core</artifactId>
				<version>6.10.4</version>
			</dependency>

**Comment by HardNorth** [comment]
@silwalrajan You want it as one launch, but someone may want it as two launches. So, do you have any stronger arguments to justify such implementation? Apart the fact that we are not an Extent Reports and don't count it as the source of the truth.

**Comment by HardNorth** [comment]
Answered
